"use client";
import { Button, Heading } from "@chakra-ui/react";
import { createBrowserSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { Inter } from "next/font/google";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

//CAN'T BE IN A CLIENT COMPONENT:
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // useContext to share this if we're going deeper with multiple client components
  // auth helpers docs: https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components?utm_source=youtube&utm_medium=referral&utm_campaign=nextjs-supabase
  const [supabase] = useState(() => createBrowserSupabaseClient());
  const router = useRouter();

  //ran into a problem when next/navigation wasn't installed as a dependency for some reason
  //next/navigation wasn't autofilling, but it works with --experimental

  useEffect(() => {
    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange(() => {
      //refresh data on login or logout
      router.refresh();
    });
    return () => {
      subscription.unsubscribe();
    };
  }, [router, supabase.auth]);

  const signUp = () => {
    supabase.auth.signUp({
      email: "user@user.com",
      password: "sup3rs3cur3",
    });
  };

  //can't use same as above since it can't be verified, so created a dummy row in the Supabase users table
  const signIn = () => {
    supabase.auth.signInWithPassword({
      email: "admin@admin.com",
      password: "admin",
    });
  };

  const signOut = () => {
    supabase.auth.signOut();
  };

  //localStorage is only a browser (client) thing, but the database request is coming from the server, so the browser token isn't enough to satisfy the "authenticated" database policy
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Button style={{ padding: "10px", margin: "10px" }} onClick={signUp}>
            Sign Up
          </Button>
          <Button style={{ padding: "10px", margin: "10px" }} onClick={signIn}>
            Sign In
          </Button>
          <Button style={{ padding: "10px", margin: "10px" }} onClick={signOut}>
            Sign Out
          </Button>
          {children}
        </Providers>
      </body>
    </html>
  );
}
